[package]
name = "tls-fragment-proxy"
version = "3.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.5"
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
dashmap = "5.5"  # Make sure this line is present
humansize = "2.1"
parking_lot = "0.12"
rand = "0.8"
thiserror = "1.0"
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wildmatch = "2.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"